# Generated by Django 3.2.25 on 2025-06-05 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitness',
            name='date_time',
            field=models.DateTimeField(),
        ),
    ]
